"""
RomM Platform Slug Mapping
Extracted from: https://docs.romm.app/4.3.0/Platforms-and-Players/Supported-Platforms/
Total platforms: 455
Date extracted: 2025-11-09
"""

ROMM_PLATFORM_SLUGS = {
    "1292 Advanced Programmable Video System": "1292-advanced-programmable-video-system",
    "3DO Interactive Multiplayer": "3do",
    "8-Bit Productions Commander X16": "commander-x16",
    "ABC 80": "abc-80",
    "APF MP1000/Imagination Machine": "apf",
    "AY-3-8500": "ay-3-8500",
    "AY-3-8603": "ay-3-8603",
    "AY-3-8605": "ay-3-8605",
    "AY-3-8606": "ay-3-8606",
    "AY-3-8607": "ay-3-8607",
    "AY-3-8610": "ay-3-8610",
    "AY-3-8710": "ay-3-8710",
    "AY-3-8760": "ay-3-8760",
    "Aamber Pegasus": "pegasus",
    "Acorn Archimedes": "acorn-archimedes",
    "Acorn Electron": "acorn-electron",
    "Advanced Pico Beena": "advanced-pico-beena",
    "Adventure Vision": "adventure-vision",
    "AirConsole": "airconsole",
    "Alice 32/90": "alice-3290",
    "Altair 680": "altair-680",
    "Altair 8800": "altair-8800",
    "Amazon Alexa": "amazon-alexa",
    "Amazon Fire TV": "amazon-fire-tv",
    "Amiga": "amiga",
    "Amiga CD": "amiga-cd",
    "Amiga CD32": "amiga-cd32",
    "Amstrad CPC": "acpc",
    "Amstrad GX4000": "amstrad-gx4000",
    "Amstrad PCW": "amstrad-pcw",
    "Analogue electronics": "analogueelectronics",
    "Android": "android",
    "Antstream": "antstream",
    "Apogee BK-01": "bk-01",
    "Apple I": "apple",
    "Apple II": "appleii",
    "Apple IIGS": "apple-iigs",
    "Apple III": "appleiii",
    "Apple Lisa": "apple-lisa",
    "Apple Pippin": "apple-pippin",
    "Arcade": "arcade",
    "Arcadia 2001": "arcadia-2001",
    "Arduboy": "arduboy",
    "Astral 2000": "astral-2000",
    "Atari 2600": "atari2600",
    "Atari 5200": "atari5200",
    "Atari 7800": "atari7800",
    "Atari 8-bit": "atari8bit",
    "Atari 800": "atari800",
    "Atari Jaguar": "jaguar",
    "Atari Jaguar CD": "atari-jaguar-cd",
    "Atari Lynx": "lynx",
    "Atari ST/STE": "atari-st",
    "Atari VCS": "atari-vcs",
    "Atari XEGS": "atari-xegs",
    "Atom": "atom",
    "BBC Microcomputer System": "bbcmicro",
    "BGR Computers Excalibur 64": "excalibur-64",
    "BREW": "brew",
    "Bada": "bada",
    "Bally Astrocade": "astrocade",
    "BeOS": "beos",
    "Benesse Pocket Challenge V2": "pocket-challenge-v2",
    "Benesse Pocket Challenge W": "pocket-challenge-w",
    "Bit Corporation BIT 90": "bit-90",
    "Black Point": "black-point",
    "BlackBerry OS": "blackberry",
    "Blacknut": "blacknut",
    "Blu-ray Player": "blu-ray-player",
    "Browser (Flash/HTML5)": "browser",
    "Bubble": "bubble",
    "CDC Cyber 70": "cdccyber70",
    "COSMAC": "fred-cosmac",
    "CP/M": "cpm",
    "Call-A-Computer time-shared mainframe computer system": "call-a-computer",
    "Cambridge Computer Z88": "z88",
    "Camputers Lynx": "camputers-lynx",
    "Casio CFX-9850": "casio-cfx-9850",
    "Casio FP-1000 & FP-1100": "casio-fp-1000",
    "Casio Loopy": "casio-loopy",
    "Casio PB-1000": "casio-pb-1000",
    "Casio PV-1000": "casio-pv-1000",
    "Casio PV-2000": "casio-pv-2000",
    "Casio Programmable Calculator": "casio-programmable-calculator",
    "Champion 2711": "champion-2711",
    "ClickStart": "clickstart",
    "Coleco Adam": "colecoadam",
    "ColecoVision": "colecovision",
    "Colour Genie": "colour-genie",
    "Commodore 128": "c128",
    "Commodore 16": "c16",
    "Commodore C64/128/MAX": "c64",
    "Commodore CDTV": "commodore-cdtv",
    "Commodore PET": "cpet",
    "Commodore Plus/4": "c-plus-4",
    "Commodore VIC-20": "vic-20",
    "Compal 80": "compal-80",
    "Compucolor I": "compucolor-i",
    "Compucolor II": "compucolor-ii",
    "Compucorp Programmable Calculator": "compucorp-programmable-calculator",
    "CreatiVision": "creativision",
    "Cybervision": "cybervision",
    "DEC GT40": "gt40",
    "DOS": "dos",
    "DVD Player": "dvd-player",
    "Danger OS": "danger-os",
    "Daydream": "daydream",
    "Dedicated console": "dedicated-console",
    "Dedicated handheld": "dedicated-handheld",
    "Didj": "didj",
    "Digiblast": "digiblast",
    "DoJa": "doja",
    "Donner Model 30": "donner30",
    "Dragon 32/64": "dragon-32-slash-64",
    "Dreamcast": "dc",
    "ECD Micromind": "ecd-micromind",
    "EDSAC": "edsac",
    "Elektor TV Games Computer": "elektor",
    "Elektronika BK": "bk",
    "Enterprise": "enterprise",
    "Epoch Cassette Vision": "epoch-cassette-vision",
    "Epoch Game Pocket Computer": "epoch-game-pocket-computer",
    "Epoch Super Cassette Vision": "epoch-super-cassette-vision",
    "Evercade": "evercade",
    "ExEn": "exen",
    "Exelvision": "exelvision",
    "Exidy Sorcerer": "exidy-sorcerer",
    "FM Towns": "fm-towns",
    "FM-7": "fm-7",
    "Fairchild Channel F": "fairchild-channel-f",
    "Family Computer": "famicom",
    "Family Computer Disk System": "fds",
    "Feature phone": "mobile-custom",
    "Ferranti Nimrod Computer": "nimrod",
    "Freebox": "freebox",
    "G-cluster": "g-cluster",
    "GIMINI": "gimini",
    "GNEX": "gnex",
    "GP2X": "gp2x",
    "GP2X Wiz": "gp2x-wiz",
    "GP32": "gp32",
    "GVM": "gvm",
    "Galaksija": "galaksija",
    "Gamate": "gamate",
    "Game & Watch": "g-and-w",
    "Game Boy": "gb",
    "Game Boy Advance": "gba",
    "Game Boy Color": "gbc",
    "Game Master": "hartung",
    "Game Wave": "game-wave",
    "Game.com": "game-dot-com",
    "GameStick": "gamestick",
    "Gear VR": "gear-vr",
    "Gizmondo": "gizmondo",
    "Gloud": "gloud",
    "Glulx": "glulx",
    "Google Stadia": "stadia",
    "HD DVD Player": "hd-dvd-player",
    "HP 2100": "hp2100",
    "HP 3000": "hp3000",
    "HP 9800": "hp-9800",
    "HP Programmable Calculator": "hp-programmable-calculator",
    "Handheld Electronic LCD": "handheld-electronic-lcd",
    "Heath/Zenith H8/H89": "heathzenith",
    "Heathkit H11": "heathkit-h11",
    "Hector HRX": "hrx",
    "Hitachi S1": "hitachi-s1",
    "Hugo": "hugo",
    "Hyper Neo Geo 64": "hyper-neo-geo-64",
    "HyperScan": "hyperscan",
    "IBM 5100": "ibm-5100",
    "IBM PCjr": "pc-jr",
    "Ideal-Computer": "ideal-computer",
    "Imlac PDS-1": "imlac-pds1",
    "Intel 8008": "intel-8008",
    "Intel 8080": "intel-8080",
    "Intel 8086 / 8088": "intel-8086",
    "Intellivision": "intellivision",
    "Intellivision Amico": "intellivision-amico",
    "Interact Model One": "interact-model-one",
    "Interton VC 4000": "interton-vc-4000",
    "Interton Video 2000": "interton-video-2000",
    "J2ME": "j2me",
    "Jolt": "jolt",
    "Jupiter Ace": "jupiter-ace",
    "KIM-1": "kim-1",
    "KaiOS": "kaios",
    "Kindle Classic": "kindle",
    "Laser 200": "laser200",
    "LaserActive": "laseractive",
    "LeapFrog Explorer": "leapfrog-explorer",
    "LeapTV": "leaptv",
    "Leapster": "leapster",
    "Leapster Explorer/LeadPad Explorer": "leapster-explorer-slash-leadpad-explorer",
    "Legacy Computer": "legacy-computer",
    "Legacy Mobile Device": "mobile",
    "Linux": "linux",
    "Luna": "luna",
    "MOS Technology 6502": "mos-technology-6502",
    "MRE": "mre",
    "MSX": "msx",
    "MSX Turbo R": "msx-turbo",
    "MSX2": "msx2",
    "MUGEN": "mugen",
    "Mac": "mac",
    "Maemo": "maemo",
    "Magnavox Odyssey": "odyssey",
    "Mainframe": "mainframe",
    "Matsushita/Panasonic JR": "matsushitapanasonic-jr",
    "Mattel Aquarius": "aquarius",
    "MeeGo": "meego",
    "Mega Duck/Cougar Boy": "mega-duck-slash-cougar-boy",
    "Memotech MTX": "memotech-mtx",
    "Memotech MTX512": "mtx512",
    "Meritum": "meritum",
    "Meta Quest 2": "meta-quest-2",
    "Meta Quest 3": "meta-quest-3",
    "Microbee": "microbee",
    "Microcomputer": "microcomputer",
    "Microsoft MSX2+": "msx2plus",
    "Microtan 65": "microtan-65",
    "Microvision": "microvision",
    "Mophun": "mophun",
    "Motorola 6800": "motorola-6800",
    "Motorola 68k": "motorola-68k",
    "N-Gage": "ngage",
    "N-Gage (service)": "ngage2",
    "NEC PC-6000 Series": "nec-pc-6000-series",
    "Namco System 22": "system-32",
    "Nascom": "nascom",
    "Neo Geo AES": "neogeoaes",
    "Neo Geo CD": "neo-geo-cd",
    "Neo Geo MVS": "neogeomvs",
    "Neo Geo Pocket": "neo-geo-pocket",
    "Neo Geo Pocket Color": "neo-geo-pocket-color",
    "Neo Geo X": "neo-geo-x",
    "New Nintendo 3DS": "new-nintendo-3ds",
    "NewBrain": "newbrain",
    "Newton": "newton",
    "Nintendo 3DS": "3ds",
    "Nintendo 64": "n64",
    "Nintendo 64DD": "64dd",
    "Nintendo DS": "nds",
    "Nintendo DSi": "nintendo-dsi",
    "Nintendo Entertainment System": "nes",
    "Nintendo GameCube": "ngc",
    "Nintendo Switch": "switch",
    "Nintendo Switch 2": "switch-2",
    "North Star": "northstar",
    "Noval 760": "noval-760",
    "Nuon": "nuon",
    "OOParts": "ooparts",
    "OS/2": "os2",
    "Oculus Go": "oculus-go",
    "Oculus Quest": "oculus-quest",
    "Oculus Rift": "oculus-rift",
    "Oculus VR": "oculus-vr",
    "Odyssey 2": "odyssey-2",
    "Odyssey 2 / Videopac G7000": "odyssey-2-slash-videopac-g7000",
    "Ohio Scientific": "ohio-scientific",
    "OnLive Game System": "onlive-game-system",
    "OpenBOR": "openbor",
    "Orao": "orao",
    "Oric": "oric",
    "Oric Atmos": "atmos",
    "Othello Multivision": "multivision",
    "Ouya": "ouya",
    "PC Booter": "pc-booter",
    "PC Engine SuperGrafx": "supergrafx",
    "PC-50X Family": "pc-50x-family",
    "PC-6001": "pc-6001",
    "PC-8000": "pc-8000",
    "PC-8800 Series": "pc-8800-series",
    "PC-9800 Series": "pc-9800-series",
    "PC-FX": "pc-fx",
    "PDP-1": "pdp1",
    "PDP-10": "pdp10",
    "PDP-11": "pdp11",
    "PDP-7": "pdp-7",
    "PDP-8": "pdp-8",
    "PICO": "pico",
    "PLATO": "plato",
    "Palm OS": "palm-os",
    "Palmtex": "palmtex",
    "Panasonic Jungle": "panasonic-jungle",
    "Panasonic M2": "panasonic-m2",
    "Pandora": "pandora",
    "Pebble": "pebble",
    "Philips CD-i": "philips-cd-i",
    "Philips VG 5000": "philips-vg-5000",
    "Photo CD": "photocd",
    "Pinball": "pinball",
    "Pippin": "pippin",
    "PlayStation": "psx",
    "PlayStation 2": "ps2",
    "PlayStation 3": "ps3",
    "PlayStation 4": "ps4",
    "PlayStation 5": "ps5",
    "PlayStation Now": "playstation-now",
    "PlayStation Portable": "psp",
    "PlayStation VR": "psvr",
    "PlayStation VR2": "psvr2",
    "PlayStation Vita": "psvita",
    "Playdate": "playdate",
    "Playdia": "playdia",
    "Plex Arcade": "plex-arcade",
    "Plug & Play": "plug-and-play",
    "PocketStation": "pocketstation",
    "Pokitto": "pokitto",
    "Pokémon mini": "pokemon-mini",
    "Poly-88": "poly-88",
    "Polymega": "polymega",
    "R-Zone": "r-zone",
    "RCA Studio II": "rca-studio-ii",
    "Research Machines 380Z": "research-machines-380z",
    "Roku": "roku",
    "SAM Coupé": "sam-coupe",
    "SC/MP": "scmp",
    "SD-200/270/290": "sd-200270290",
    "SDS Sigma 7": "sdssigma7",
    "SG-1000": "sg1000",
    "SK-VM": "sk-vm",
    "SMC-777": "smc-777",
    "SRI-500/1000": "sri-5001000",
    "SWTPC 6800": "swtpc-6800",
    "Satellaview": "satellaview",
    "ScummVM": "scummvm",
    "Sega 32X": "sega32",
    "Sega Advanced Pico Beena": "beena",
    "Sega CD": "segacd",
    "Sega CD 32X": "segacd32",
    "Sega Dreamcast VMU": "vmu",
    "Sega Game Gear": "gamegear",
    "Sega Hikaru": "hikaru",
    "Sega Master System/Mark III": "sms",
    "Sega Mega Drive/Genesis": "genesis",
    "Sega Model 1": "model1",
    "Sega Model 2": "model2",
    "Sega Model 3": "model3",
    "Sega Pico": "sega-pico",
    "Sega SC-3000": "sc3000",
    "Sega ST-V": "stv",
    "Sega Saturn": "saturn",
    "Sega System 16": "system16",
    "Sega System 32": "system32",
    "Sharp MZ-2200": "sharp-mz-2200",
    "Sharp MZ-80B/2000/2500": "sharp-mz-80b20002500",
    "Sharp MZ-80K/700/800/1500": "sharp-mz-80k7008001500",
    "Sharp X1": "x1",
    "Sharp X68000": "sharp-x68000",
    "Sharp Zaurus": "sharp-zaurus",
    "Signetics 2650": "signetics-2650",
    "Sinclair QL": "sinclair-ql",
    "Sinclair ZX81": "zx81",
    "Socrates": "socrates",
    "Sol-20": "sol-20",
    "Sony PSP Minis": "psp-minis",
    "Sord M5": "sord-m5",
    "Spectravideo": "spectravideo",
    "SteamVR": "steam-vr",
    "Sufami Turbo": "sufami-turbo",
    "Super A'Can": "super-acan",
    "Super Famicom": "sfam",
    "Super NES CD-ROM System": "super-nes-cd-rom-system",
    "Super Nintendo Entertainment System": "snes",
    "Super Vision 8000": "super-vision-8000",
    "Sure Shot HD": "sure-shot-hd",
    "SwanCrystal": "swancrystal",
    "Symbian": "symbian",
    "TADS": "tads",
    "TI Programmable Calculator": "ti-programmable-calculator",
    "TI-99/4A": "ti-994a",
    "TIM": "tim",
    "TRS-80": "trs-80",
    "TRS-80 Color Computer": "trs-80-color-computer",
    "TRS-80 MC-10": "trs-80-mc-10",
    "TRS-80 Model 100": "trs-80-model-100",
    "Taito Type X": "type-x",
    "Taito X-55": "taito-x-55",
    "Tandy Vis": "tandy-vis",
    "Tapwave Zodiac": "zod",
    "Tatung Einstein": "tatung-einstein",
    "Tektronix 4050": "tektronix-4050",
    "Tele-Spiel ES-2201": "tele-spiel",
    "Telstar Arcade": "telstar-arcade",
    "Terebikko / See 'n Say Video Phone": "terebikko-slash-see-n-say-video-phone",
    "Terminal": "terminal",
    "Texas Instruments TI-82": "ti-82",
    "Texas Instruments TI-83": "ti-83",
    "Texas Instruments TI-99": "ti-99",
    "Thomson MO5": "thomson-mo5",
    "Thomson TO": "thomson-to",
    "Tiki 100": "tiki-100",
    "Timex Sinclair 2068": "timex-sinclair-2068",
    "Tizen": "tizen",
    "Tomahawk F1": "tomahawk-f1",
    "Tomy Tutor": "tomy-tutor",
    "Tomy Tutor / Pyuta / Grandstand Tutor": "tomy-tutor-slash-pyuta-slash-grandstand-tutor",
    "Triton": "triton",
    "TurboGrafx-16/PC Engine": "tg16",
    "Turbografx-16/PC Engine CD": "turbografx-cd",
    "Uzebox": "uzebox",
    "V.Flash": "vflash",
    "V.Smile": "vsmile",
    "VC 4000": "vc-4000",
    "VIS": "vis",
    "Vector-06C": "06c",
    "Vectrex": "vectrex",
    "Versatile": "versatile",
    "VideoBrain": "videobrain",
    "Videopac+ G7400": "videopac-g7400",
    "Virtual Boy": "virtualboy",
    "Virtual Console": "vc",
    "Visual Memory Unit / Visual Memory System": "visual-memory-unit-slash-visual-memory-system",
    "WASM-4": "wasm-4",
    "WIPI": "wipi",
    "Wang 2200": "wang2200",
    "Watara/QuickShot Supervision": "supervision",
    "Wii": "wii",
    "Wii U": "wiiu",
    "Windows": "win",
    "Windows 3.x": "win3x",
    "Windows Apps": "windows-apps",
    "Windows Mixed Reality": "windows-mixed-reality",
    "Windows Mobile": "windows-mobile",
    "Windows Phone": "winphone",
    "WoW Action Max": "action-max",
    "WonderSwan": "wonderswan",
    "WonderSwan Color": "wonderswan-color",
    "XaviXPORT": "xavixport",
    "Xbox": "xbox",
    "Xbox 360": "xbox360",
    "Xbox Cloud Gaming": "xboxcloudgaming",
    "Xbox One": "xboxone",
    "Xbox Series X": "series-x-s",
    "Xerox Alto": "xerox-alto",
    "Z-machine": "z-machine",
    "ZX Spectrum": "zxs",
    "ZX Spectrum Next": "zx-spectrum-next",
    "ZX80": "zx80",
    "Zeebo": "zeebo",
    "ZiNc": "zinc",
    "Zilog Z80": "z80",
    "Zilog Z8000": "zilog-z8000",
    "Zodiac": "zodiac",
    "Zune": "zune",
    "e-Reader / Card-e Reader": "e-reader-slash-card-e-reader",
    "iOS": "ios",
    "iPad": "ipad",
    "iPod Classic": "ipod-classic",
    "iiRcade": "iircade",
    "tvOS": "tvos",
    "visionOS": "visionos",
    "watchOS": "watchos",
    "webOS": "webos",
}

# Common aliases and alternative names
PLATFORM_ALIASES = {
    "3DO": "3do",
    "3DS": "3ds",
    "Amiga": "amiga",
    "Arcade": "arcade",
    "Atari 2600": "atari2600",
    "Atari 5200": "atari5200",
    "Atari 7800": "atari7800",
    "C64": "c64",
    "Commodore 64": "c64",
    "DOS": "dos",
    "DS": "nds",
    "Dreamcast": "dc",
    "Famicom": "famicom",
    "GBA": "gba",
    "GBC": "gbc",
    "Game Boy": "gb",
    "Game Gear": "gamegear",
    "GameCube": "ngc",
    "Genesis": "genesis",
    "Jaguar": "jaguar",
    "Linux": "linux",
    "Lynx": "lynx",
    "MAME": "arcade",
    "Mac": "mac",
    "Master System": "sms",
    "Mega Drive": "genesis",
    "N64": "n64",
    "NES": "nes",
    "NGP": "neo-geo-pocket",
    "NGPC": "neo-geo-pocket-color",
    "Neo Geo": "neogeoaes",
    "Neo Geo AES": "neogeoaes",
    "Neo Geo MVS": "neogeomvs",
    "Neo Geo Pocket": "neo-geo-pocket",
    "PC": "win",
    "PC Engine": "tg16",
    "PCE": "tg16",
    "PS Vita": "psvita",
    "PS1": "psx",
    "PS2": "ps2",
    "PS3": "ps3",
    "PS4": "ps4",
    "PS5": "ps5",
    "PSP": "psp",
    "PlayStation": "psx",
    "SNES": "snes",
    "Saturn": "saturn",
    "Spectrum": "zxs",
    "Super Famicom": "sfam",
    "Switch": "switch",
    "TG16": "tg16",
    "TurboGrafx-16": "tg16",
    "Vita": "psvita",
    "Wii": "wii",
    "Wii U": "wiiu",
    "Windows": "win",
    "Xbox": "xbox",
    "Xbox 360": "xbox360",
    "Xbox One": "xboxone",
    "ZX Spectrum": "zxs",
    "macOS": "mac",
}
